Vision Config, Dual Camera Use, And Expanding Unicorn Functions To Climb
FirewallRobotics/2024-Zenith pull request #153
Opened 2024-03-13 22:39 UTC by NoobinOut

2024-03-14 23:21 UTC, Wendydarby requested changes, later dismissed
see comments

2024-03-14 23:21 UTC, Wendydarby commented on src/orangepi/ProductionFiles/FinalPiProgram.py
> +
I recommend the CS.enableLogging() from the myCamPub.py to enable the logging within the CameraServer code.

2024-03-14 23:21 UTC, Wendydarby commented on src/orangepi/ProductionFiles/FinalPiProgram.py
>          output = denoise_image(output)
what is output? where is that coming from???  is this supposed to be denoise_image(output)???

2024-03-16 16:35 UTC, HarperStumb approved these changes

2024-03-16 16:35 UTC, merged